/**
 * Creates the Phase B wallet and writes its key straight into `.env`.
 *
 *   npx ts-node scripts/new-treasury-wallet.ts          # plan only
 *   npx ts-node scripts/new-treasury-wallet.ts --write  # create and persist
 *
 * WHY A SCRIPT AND NOT `Wallet.createRandom()` IN A TERMINAL
 * ----------------------------------------------------------
 * The obvious one-liner prints the private key to stdout, which puts it in the terminal
 * scrollback, in any shell history that captures output, in a screenshot, and in a chat log if
 * it is ever pasted to ask a question about it. A key that controls money should be written
 * once, to one file that is already gitignored, and never rendered anywhere else.
 *
 * This prints the **address only**. The private key goes directly to `backend/.env`.
 *
 * ⚠️ THIS IS NOT THE PRODUCTION TREASURY.
 * `docs/SECURITY-BOUNDARIES.md` item 5 is explicit: a bare key in an env file must never hold
 * real operating funds, and `RawKeyTreasurySigner` refuses to run under NODE_ENV=production
 * for that reason. Phase B is a deliberate, bounded exception -- a wallet holding ~0.01 ETH
 * for one self-dealt validation launch. When the bot goes live for users, the treasury is a
 * Turnkey signer with a policy scoped to the factory, and this wallet is drained and retired.
 *
 * Fund it with a small amount and no more. Treat the balance as spent.
 */
import { ethers } from 'ethers';
import * as fs from 'fs';
import * as path from 'path';

const ENV_PATH = path.join(__dirname, '..', '.env');
const KEY = 'TREASURY_SIGNER_PRIVATE_KEY';
/** Enough for the launch fee plus gas for two transactions and a couple of test swaps. */
const SUGGESTED_FUNDING_ETH = '0.01';

function readEnv(): string {
  if (!fs.existsSync(ENV_PATH)) return '';
  return fs.readFileSync(ENV_PATH, 'utf8');
}

function existingKey(contents: string): string | null {
  for (const line of contents.split(/\r?\n/)) {
    const match = line.match(/^\s*TREASURY_SIGNER_PRIVATE_KEY\s*=\s*(.*)$/);
    if (match && match[1].trim().length > 0) return match[1].trim();
  }
  return null;
}

function main() {
  const WRITE = process.argv.includes('--write');
  const contents = readEnv();
  const already = existingKey(contents);

  if (already) {
    // Refusing here is the whole point. Overwriting a funded key orphans its balance with no
    // way back -- and the balance is exactly what someone would be re-running this to fix.
    let address = '(unreadable -- the value in .env is not a valid private key)';
    try {
      address = new ethers.Wallet(already).address;
    } catch {
      /* leave the placeholder */
    }
    console.error(`${KEY} is already set in backend/.env.`);
    console.error(`  address: ${address}`);
    console.error('');
    console.error('Refusing to overwrite it. If that wallet holds any balance, replacing the key');
    console.error('strands the funds permanently. To deliberately start over, move the existing');
    console.error('balance out first, then delete the line from .env by hand and re-run this.');
    process.exit(1);
  }

  if (!WRITE) {
    console.log('PLAN ONLY: would generate a Phase B wallet and append its private key to backend/.env.');
    console.log('No wallet was generated and no file was changed. Re-run with --write to proceed.');
    return;
  }

  const wallet = ethers.Wallet.createRandom();

  const needsNewline = contents.length > 0 && !contents.endsWith('\n');
  const block =
    (needsNewline ? '\n' : '') +
    '\n# Phase B wallet, generated by scripts/new-treasury-wallet.ts.\n' +
    '# Testnet + one self-dealt mainnet validation launch ONLY. Never the production treasury\n' +
    '# -- see docs/SECURITY-BOUNDARIES.md item 5. Fund it small; treat the balance as spent.\n' +
    `${KEY}=${wallet.privateKey}\n`;

  fs.appendFileSync(ENV_PATH, block, { encoding: 'utf8', mode: 0o600 });

  console.log('Wallet created. The private key was written to backend/.env and is not shown here.');
  console.log('');
  console.log('  ADDRESS TO FUND');
  console.log(`  ${wallet.address}`);
  console.log('');
  console.log(`  Network   Robinhood Chain mainnet (chain 4663)`);
  console.log(`  Amount    ~${SUGGESTED_FUNDING_ETH} ETH is plenty`);
  console.log('');
  console.log('             0.0005  launch fee');
  console.log('             0.002   gas reserve (splitter deploy + launch are two transactions)');
  console.log('             rest    a couple of small swaps, to generate real trading fees');
  console.log('');
  console.log('Bridge only via the canonical Arbitrum bridge or a partner named in');
  console.log('docs.robinhood.com/chain/bridging. Fake Robinhood Chain bridge sites exist.');
  console.log('');
  console.log('Then check it arrived:');
  console.log('  RPC_URL=https://rpc.mainnet.chain.robinhood.com CHAIN_ID=4663 \\');
  console.log('    npx ts-node scripts/phase-b-launch.ts');
}

main();
